apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cast-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cast-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cast-service.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: DATABASE_URI
              value: "postgresql://admin:password@db:5432/storedb"

