apiVersion: v1
kind: Service
metadata:
  name: { include "cast-service.fullname" . }
spec:
  type: { .Values.service.type }
  selector:
    app: { include "cast-service.name" . }
  ports:
    - port: { .Values.service.port }
      targetPort: { .Values.service.targetPort }
