replicaCount: 1

image:
  repository: riadriri/cast-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false

resources: {}
